openapi: 3.0.0
info:
  title: Policy Mate Authentication API
  version: 1.0.0
  description: API for authenticating users and retrieving claims
paths:
  /authenticate:
    post:
      summary: Authenticate user with bearer token
      description: Validates bearer token and returns user claims. This must be called first before any other operations.
      operationId: authenticateUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - token
              properties:
                token:
                  type: string
                  description: Bearer token from user authentication
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  sub:
                    type: string
                    description: User ID
                  email:
                    type: string
                    description: User email
                  cognito:username:
                    type: string
                    description: Username
        '400':
          description: Bad request - token missing or invalid format
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '401':
          description: Unauthorized - invalid or expired token
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
