openapi: 3.0.0
info:
  title: Policy Mate Conversation History API
  version: 1.0.0
  description: API for retrieving conversation history with pagination
paths:
  /conversations:
    get:
      summary: Get conversation history
      description: Retrieve messages or sessions with pagination support
      operationId: getConversationHistory
      parameters:
        - name: action
          in: query
          required: true
          schema:
            type: string
            enum: [get_messages, get_sessions]
          description: Action to perform
        - name: session_id
          in: query
          required: false
          schema:
            type: string
          description: Session ID (required for get_messages)
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 20
            minimum: 1
            maximum: 100
          description: Number of items per page
        - name: last_key
          in: query
          required: false
          schema:
            type: string
          description: JSON-encoded pagination token from previous response
        - name: newest_first
          in: query
          required: false
          schema:
            type: boolean
            default: true
          description: Sort order for messages (get_messages only)
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/MessagesResponse'
                  - $ref: '#/components/schemas/SessionsResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Cognito JWT ID token
  schemas:
    MessagesResponse:
      type: object
      properties:
        messages:
          type: array
          items:
            type: object
            properties:
              message_id:
                type: string
              session_id:
                type: string
              user_id:
                type: string
              role:
                type: string
                enum: [user, assistant]
              content:
                type: string
              timestamp:
                type: string
                format: date-time
        next_page_token:
          type: object
          nullable: true
          description: Pass this to last_key parameter for next page
        has_more:
          type: boolean
    SessionsResponse:
      type: object
      properties:
        sessions:
          type: array
          items:
            type: object
            properties:
              session_id:
                type: string
              user_id:
                type: string
              last_message_time:
                type: string
                format: date-time
        next_page_token:
          type: object
          nullable: true
        has_more:
          type: boolean
