openapi: 3.0.0
info:
  title: Policy Mate Document Management API
  version: 1.0.0
  description: API for uploading and managing policy documents
paths:
  /ingest:
    post:
      summary: Upload a policy document
      description: Upload and store a policy document file. Accepts base64 encoded file content.
      operationId: ingestPolicy
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - filename
                - file
                - type
                - claims
              properties:
                filename:
                  type: string
                  description: Name of the file to upload (e.g., policy.pdf)
                file:
                  type: string
                  description: Base64 encoded file content
                type:
                  type: string
                  enum:
                    - custom
                    - standard
                  description: Document type - custom for user documents, standard for admin-only documents
                claims:
                  type: object
                  description: User claims from authentication (must be obtained from authenticateUser first)
                  required:
                    - sub
                    - custom:org_id
                  properties:
                    sub:
                      type: string
                      description: User ID
                    custom:org_id:
                      type: string
                      description: Organization ID
                    custom:user_role:
                      type: string
                      description: User role
      responses:
        '200':
          description: File uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Success message
                  metadata:
                    type: object
                    description: File metadata including file_id, s3_path, upload_date
        '400':
          description: Bad request - invalid file type, size, or missing required fields
        '403':
          description: Forbidden - user not authorized to upload standard documents
