[project]
name = "policy-mate-lambda"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "aws-lambda-typing>=2.20.0",
    "python-dotenv>=1.0.0",
    "python-jose[cryptography]>=3.3.0",
    "requests>=2.32.0",
    "requests-aws4auth>=1.3.1",
    "strands-agents>=1.13.0",
    "strands-agents-tools>=0.2.12",
    "typing-extensions>=4.15.0",
    "uuid6>=2025.0.1",
]
