[project]
name = "policy-mate-file-confirmation-lambda"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "aws-lambda-typing>=2.20.0",
    "python-dotenv>=1.0.0",
    "python-jose[cryptography]>=3.3.0",
    "pymupdf>=1.26.5",
    "pypdf>=6.1.1",
    "requests>=2.32.0",
    "requests-aws4auth>=1.3.1",
    "uuid6>=2025.0.1",
]
