default_agent: policyMate
agents:
  policyMate:
    name: policyMate
    entrypoint: /home/shivamsahil/projects/2025/oct/policy_mate/lambdas/deploy_agent.py
    platform: linux/arm64
    container_runtime: none
    source_path: /home/shivamsahil/projects/2025/oct/policy_mate/lambdas
    aws:
      execution_role: arn:aws:iam::354468042457:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-2796fe729f
      execution_role_auto_create: false
      account: '354468042457'
      region: us-east-1
      ecr_repository: 354468042457.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-policymate
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: policyMate-WoQ1uB3z5m
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:354468042457:runtime/policyMate-WoQ1uB3z5m
      agent_session_id: a4cd78dd-2352-4ffa-ad6d-fc271f2ab589
    codebuild:
      project_name: bedrock-agentcore-policymate-builder
      execution_role: arn:aws:iam::354468042457:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-2796fe729f
      source_bucket: bedrock-agentcore-codebuild-sources-354468042457-us-east-1
    memory:
      mode: STM_ONLY
      memory_id: policyMate_mem-HwSbs34YoA
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:354468042457:memory/policyMate_mem-HwSbs34YoA
      memory_name: policyMate_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
