[project]
name = "policy-mate-lambda"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "aws-lambda-typing>=2.20.0",
    "boto3>=1.35.0",
    "boto3-stubs[s3,dynamodb]>=1.40.45",
    "opensearch-py>=3.0.0",
    "python-dotenv>=1.0.0",
    "python-jose[cryptography]>=3.3.0",
    "requests>=2.32.0",
    "requests-aws4auth>=1.3.1",
]
